$env:SQL_SERVER_EDITION = 'EXPRESS' # EXPRESS or DEVELOPER.
$env:SQL_SERVER_INSTANCE_NAME = "SQL$env:SQL_SERVER_EDITION"
$env:SQL_SERVER_INSTANCE = "$env:COMPUTERNAME\$env:SQL_SERVER_INSTANCE_NAME"
$env:SQL_SERVER_SERVICE_NAME = "MSSQL`$$env:SQL_SERVER_INSTANCE_NAME"
