$env:SQL_SERVER_EDITION = 'EXPRESS' # EXPRESS, STANDARD-DEVELOPER or ENTERPRISE-DEVELOPER.
$env:SQL_SERVER_INSTANCE_NAME = 'SQLSERVER'
$env:SQL_SERVER_INSTANCE = "$env:COMPUTERNAME\$env:SQL_SERVER_INSTANCE_NAME"
$env:SQL_SERVER_SERVICE_NAME = "MSSQL`$$env:SQL_SERVER_INSTANCE_NAME"
